# Generated by Django 4.2.11 on 2024-04-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doctor_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='doctor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='doctor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
